FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
python3 \
ruby-full \
&& apt-get clean && rm -rf /var/lib/apt/lists/*
COPY dbscripts/ /scripts/
COPY entrypoint.sh /scripts/
ENTRYPOINT ["/bin/bash", "/scripts/entrypoint.sh"]
